# e.g. ansible-playbook hosts.yml
---
- name: check env
  hosts: localhost
  any_errors_fatal: true
  become: false

  tasks:
    # Check version of ansible
    - name: assert ansible version
      assert:
        that:
          - "{{ ansible_version.string | version_compare('2.2', '>=') }}"
        msg: Ansible 2.2 or above is required

# - name: Initial hosts
#   hosts: cdh-test
#   become: true
#
#   tasks:
#     - name: insert hosts
#       shell: echo {{ item }} >> /etc/hosts
#       loop:
#         - ""
#         - "# CDH Nodes"
#         - "192.168.1.152	cdh-test-cluster-0"
#         - "192.168.1.156	cdh-test-cluster-1"
#         - "192.168.1.160	cdh-test-cluster-2"
#         - "192.168.1.154	cdh-test-cluster-3"
#         - "192.168.1.151	cdh-test-cluster-4"
#
#     - name: distribute private key file
#       copy:
#         src: /home/ansible/.ssh/id_rsa
#         dest: /home/ubuntu/.ssh/id_rsa
#         owner: ubuntu
#         group: ubuntu
#         mode: 0600

- name: Bind inner IP
  hosts: cdh-test
  become: true
  vars:
    inner_brt: "10.11.200.255"

#   tasks:
#     - name: Add address
#       shell: ip address add {{ inner_ip }}/24 broadcast {{ inner_brt }} dev ens6
#
#     - name: Bring up nic
#       shell: ip link set ens6 up

  tasks:
    - name: Update hosts
      shell: echo {{ item }} >> /etc/hosts
      loop:
        - ""
        - "# Inner Nodes"
        - "10.11.200.4	node-0"
        - "10.11.200.3	node-1"
        - "10.11.200.7	node-2"
        - "10.11.200.11	node-3"
        - "10.11.200.9	node-4"

