# e.g. ansible-playbook modify_ulimit.yml -e "target_hosts=anjian_test username=hadoop nofile=65536 nproc=65536"
---
- hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: configure system settings, file descriptors and number of threads
      pam_limits:
        domain: "{{ username }}"
        limit_type: "{{ item.limit_type }}"
        limit_item: "{{ item.limit_item }}"
        value: "{{ item.value }}"
      with_items:
        - { limit_type: '-', limit_item: 'nofile', value: "{{ nofile }}" }
        - { limit_type: '-', limit_item: 'nproc', value: "{{ nproc }}" }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

    - name: reload settings from all system configuration files
      shell: sysctl --system
